# Generated by Django 2.2.6 on 2019-11-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkname', models.CharField(max_length=100)),
                ('bkauth', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('bkcatgory', models.CharField(max_length=30)),
                ('bkedtion', models.CharField(max_length=30)),
                ('seller_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('seller_address', models.CharField(max_length=500)),
                ('seller_email', models.CharField(max_length=80)),
            ],
        ),
    ]
